[package]
name = "biblatex"
version = "0.1.0"
authors = ["Martin Haug <mhaug@live.de>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/typst/biblatex"
edition = "2018"

[dependencies]
anyhow = "1.0.32"
chinese-number = "0.6.0"
chrono = { version = "0.4.15", default-features = false }
lazy_static = "1.4.0"
numerals = "0.1.4"
regex = "1.3.9"
strum = "0.19.2"
strum_macros = "0.19.2"
paste = "1.0.0"
unicode-normalization = "0.1.13"
unicode-xid = "0.2"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "benchmarks"
path = "benches/benchmarks.rs"
harness = false
